/* ============================================================
   jojyy & me — content data
   150 "Open When..." cards + 150 reasons why I love Goji.
   Swap the localStorage calls in app.js for Firebase calls later —
   this file itself never needs to change.
   ============================================================ */

const openWhenCards = [
  { id: 1, question: "Open when you feel down for no reason?", answer: "Close your eyes and take a deep breath. It is completely okay to feel this way sometimes, and you don't need to justify it. Just remember that someone out here loves you beyond words, is fighting for your happiness every single day, and is sending you the warmest warm hug right now." },
  { id: 2, question: "Open when you are stressed about your studies or work?", answer: "I know how hard you push yourself and how dedicated you are. Remember that your output never defines your worth — you are the smartest, most remarkable girl in my eyes. Take a break, drink your favorite beverage, and remember our future home will be a place free of stress." },
  { id: 3, question: "Open when overthinking keeps you awake at night?", answer: "Turn off the lights and focus on my words. Let go of the heavy thoughts and let me do the worrying for us. I am working every day to build our life together. Leave the anxiety to me, rest easy, and sleep knowing you are completely safe in my heart." },
  { id: 4, question: "Open when you are upset with me?", answer: "I am truly sorry from the bottom of my heart, even before you tell me what I did wrong. Making those beautiful eyes sad is the last thing I ever want to do on this earth. Please reach out to me — your peace of mind means everything to me, and I will do whatever it takes to make it right." },
  { id: 5, question: "Open when you can't wait for our wedding day?", answer: "That live timer on our site isn't just ticking away seconds; it is bringing us closer to the morning I wake up to your beautiful face next to me. Every passing day is one step closer to our warm, peaceful home. Hang in there, my whole world!" },
  { id: 6, question: "Open when your energy levels hit zero?", answer: "Drop everything you're doing right now. Rest your head on the pillow and remember you don't have to be strong all the time. Let me re-energize you: I am madly in love with you, utterly devoted to you, and your happiness is my main drive in life." },
  { id: 7, question: "Open on July 1st (Our Special Anniversary)?", answer: "On this exact day, my entire life turned around and became illuminated by your presence. July 1st isn't just a date; it's my true birthdate — the day I learned what real love and absolute devotion to Goji mean. Happy anniversary, my light!" },
  { id: 8, question: "Open when you look in the mirror and miss me?", answer: "Look closely at the mirror. See that beautiful, respectful, elegant girl standing there? She is my entire world, the one who stole my heart, and the person I proudly brag about to everyone. Give yourself a tight hug on my behalf until I can do it myself." },
  { id: 9, question: "Open when you feel lonely and need reassurance?", answer: "You are never truly alone, Goji. Even when miles separate us physically, my mind, prayers, and heart are constantly wrapped around you. You are deeply cherished and never forgotten for a single second." },
  { id: 10, question: "Open when life feels overwhelming?", answer: "Pause for a minute. The world can be loud and demanding, but you don't have to carry it all on your shoulders. Lean on me, take one tiny step at a time, and remember that we are a team — we face everything together." },
  { id: 11, question: "Open when you are overjoyed and want to share it with me?", answer: "Your happiness is literally my favorite thing in the universe! Seeing you smile and feel accomplished brings me more joy than anything else. Tell me every detail — I want to celebrate you!" },
  { id: 12, question: "Open when you feel proud of an accomplishment?", answer: "I am bursting with pride, but honestly, I am never surprised by your greatness! You are capable of achieving anything you set your mind to, and I will always be your biggest fan cheering loudest from the front row." },
  { id: 13, question: "Open when a wave of jealousy hits you?", answer: "Let me reassure you right now: my eyes, heart, and soul are completely occupied by you and you alone. No one else exists in my world. You are my first, my last, and my forever choice." },
  { id: 14, question: "Open when you doubt yourself?", answer: "If you ever lose sight of how extraordinary you are, just look at yourself through my eyes. You are brilliant, beautiful, deeply respected, and capable of overcoming any obstacle in your path." },
  { id: 15, question: "Open when you feel confused and indecisive?", answer: "Take a deep breath and clear your mind. You don't have to figure everything out in one moment. Talk it through with me, and together we will figure out the best path forward." },
  { id: 16, question: "Open when you are bored and scrolling aimlessly?", answer: "Put down the feed! Instead of scrolling, think about three things we are going to do on our very first trip together after we get married. Send me your choices right now!" },
  { id: 17, question: "Open when you need someone to truly listen?", answer: "I am right here, fully present. Tell me everything — the good, the bad, or the random thoughts in your head. I am here to listen without judgment, always." },
  { id: 18, question: "Open when tears stream down your face?", answer: "I wish I could be there to wipe those tears away with my hands. Your tears are too precious to waste on temporary troubles. Cry it out if you must, but remember I am holding your heart safely in mine." },
  { id: 19, question: "Open when you miss hearing my voice?", answer: "If I can't call you this very second, close your eyes and recall my voice saying your name softly. I am constantly thinking about you, and I will call you the very moment I can." },
  { id: 20, question: "Open when you just woke up and feel groggy?", answer: "Good morning, gorgeous! I hope you slept well. Stretch out, take it easy, and start your day knowing that you are the very first thought on my mind every morning." },
  { id: 21, question: "Open when you need a sweet text with your coffee?", answer: "Sip your coffee slowly and enjoy this reminder: out of millions of people, you are the one who brought warmth, meaning, and true joy to my life. Enjoy your morning, beautiful." },
  { id: 22, question: "Open when you reminisce about our first day together?", answer: "That day changed everything forever. I had no idea that one day would bring me my life partner, my best friend, and my whole heart. Thank you for entering my life." },
  { id: 23, question: "Open when the world feels too fast and you need to slow down?", answer: "Stop the clock for a minute. Close your eyes, exhale slowly, and disconnect from the noise around you. Nothing is more important right now than your inner peace." },
  { id: 24, question: "Open when you have had a long, exhausting day?", answer: "You made it through the day, my champion. Now it's time to rest, unwind, and forget about all the chores or duties. You worked hard, and I am so proud of you." },
  { id: 25, question: "Open when you are under immense pressure?", answer: "Remember how resilient you are. Pressure is temporary, but your strength and my unwavering support for you are permanent. We will get through this smoothly." },
  { id: 26, question: "Open when nostalgia hits and you miss our old memories?", answer: "Our past memories are precious treasure, but remember that the absolute best chapters of our lives haven't even been written yet. The best is truly yet to come." },
  { id: 27, question: "Open when you need a little words of encouragement?", answer: "You have got this! You possess the grace, intelligence, and dignity to handle anything in front of you. Go show the world what you are made of!" },
  { id: 28, question: "Open when you feel optimistic about the day ahead?", answer: "Hold onto that beautiful energy! Spread your light, enjoy every moment today, and remember that good things are continually heading your way." },
  { id: 29, question: "Open when you get home completely drained?", answer: "Welcome back to your safe space. Kick off your shoes, relax, and let your body recover. You deserve all the rest and quiet in the world tonight." },
  { id: 30, question: "Open on the morning of your birthday?", answer: "Happy Birthday to the girl who holds my heart! Today the world was blessed with the most beautiful soul. May this year bring us even closer to fulfilling all our dreams." },
  { id: 31, question: "Open on New Year's Eve right at midnight?", answer: "Happy New Year, my love! My only goal for every coming year is to love you deeper, protect your smile, and make our dream home a reality." },
  { id: 32, question: "Open on the first rainy day of winter?", answer: "Look at the rain outside! Make a hot cup of tea, wrap yourself in a warm blanket, and say a prayer for us. Rain always reminds me of mercy, warmth, and you." },
  { id: 33, question: "Open when the night sky is clear and full of stars?", answer: "Look up at the brightest star in the sky right now. As bright as it shines, it doesn't even come close to the way your eyes light up my life every single day." },
  { id: 34, question: "Open the night before an exam or an important interview?", answer: "Take a deep breath and trust your preparation. You have prepared well, you are sharp, and you will do amazingly. Sleep well tonight; tomorrow is your day to shine." },
  { id: 35, question: "Open right after finishing a tough week or exam period?", answer: "FREEDOM! You did it! The hard work is behind you now. It's time to treat yourself, relax completely, and celebrate making it through like a boss." },
  { id: 36, question: "Open on the first day of Ramadan?", answer: "Ramadan Mubarak, my precious Goji! May this holy month bring endless blessings, peace, and light to your heart and family. You are always in my prayers." },
  { id: 37, question: "Open on Eid morning?", answer: "Eid Mubarak, my beauty! Seeing you happy on Eid makes the holiday ten times sweeter for me. Wishing you a day filled with joy, laughter, and family warmth." },
  { id: 38, question: "Open when winter starts and you feel cold?", answer: "Put on your favorite warm sweater, grab a hot drink, and let this message warm your heart: my love for you is a constant flame that will keep you warm forever." },
  { id: 39, question: "Open when you wear a new outfit and feel confident?", answer: "I don't even need to see it to know you look like absolute royalty! Your grace, modesty, and style elevate whatever you wear. You are stunning!" },
  { id: 40, question: "Open when the weather outside is calm and beautiful?", answer: "Step outside for a second and enjoy the gentle breeze. Weather like this always reminds me of your peaceful presence and delicate nature." },
  { id: 41, question: "Open when we travel somewhere new together?", answer: "Here we are, exploring the world together! Every landmark is better because you are standing beside me. Let's make memories that last a lifetime." },
  { id: 42, question: "Open when you visit a place you have always dreamed of?", answer: "Seeing your eyes light up as your dream comes true is the best gift ever. I promise to keep working hard so we can cross off every dream on our list." },
  { id: 43, question: "Open when you are walking outside alone?", answer: "Walk with confidence, princess. Remember that somewhere out there, a man is working relentlessly to build a life worthy of you and your future together." },
  { id: 44, question: "Open when our favorite song starts playing?", answer: "Turn up the volume! Every note of this song belongs to us. No matter where we are, this melody will always bridge the gap between our hearts." },
  { id: 45, question: "Open when you are doing skincare or pampering yourself?", answer: "Self-care time! Enjoy every second of pampering yourself, queen. You deserve to feel relaxed, refreshed, and cherished every single day." },
  { id: 46, question: "Open when you buy something new that makes you happy?", answer: "Congratulations on your new pick! If it brought a smile to your face, then it was worth every single penny. Enjoy it to the fullest!" },
  { id: 47, question: "Open on a busy day when we barely have time to talk?", answer: "Even on the busiest days when messages are short, please know you never leave my heart. I am sending you a quiet hug across the busyness." },
  { id: 48, question: "Open when you receive a surprise gift?", answer: "Surprise! A little token to remind you that you don't need a special occasion to be celebrated. You are loved every ordinary day." },
  { id: 49, question: "Open when you miss me and I cannot reply instantly?", answer: "I am probably tied up with work or responsibilities right now, but as soon as my hands are free, you are the first person I will reach out to. Hold on tight!" },
  { id: 50, question: "Open when you picture our future home together?", answer: "Picture it clearly: warm lighting, quiet evenings, cozy furniture we picked together, and endless laughter. That home is coming soon, I promise." },
  { id: 51, question: "Open when you imagine our wedding day and its surprises?", answer: "It will be the proudest day of my life when I hold your hand in front of everyone and start our life as husband and wife. You will be the most magnificent bride ever." },
  { id: 52, question: "Open when you look at an old picture of us?", answer: "Look how far we've come! That picture captured a moment in time, but my love for you has grown exponentially deeper since that photo was taken." },
  { id: 53, question: "Open when you think about our first trip as a married couple?", answer: "Destination chosen, bags packed, and no more goodbyes at the end of the day! Just you and me exploring new horizons together forever." },
  { id: 54, question: "Open when you wish we could meet up right this second?", answer: "I wish I could teleport to you right now! Close your eyes for five seconds and imagine me standing right there holding your hand. I'll be there soon." },
  { id: 55, question: "Open when you wonder what I am thinking about right now?", answer: "Spoiler alert: 99% chance I am thinking about your smile, working on our future, or replaying a sweet conversation we had recently. You occupy my mind." },
  { id: 56, question: "Open when you think about the little details between us?", answer: "Those inside jokes, quiet glances, and small habits are what make us unique. I treasure every little detail that belongs only to you and me." },
  { id: 57, question: "Open when you wake up from a sweet dream about us?", answer: "Dreams are lovely, but the best part is that our real-life love story is even better than any dream. Let's make that dream come true in real life!" },
  { id: 58, question: "Open when you recall something sweet I said long ago?", answer: "I meant every single word back then, and I mean it even more today. My feelings for you aren't temporary — they are rooted deep in my soul." },
  { id: 59, question: "Open when you are somewhere and wish I was sitting beside you?", answer: "Save a seat for me in your mind! One day soon, every empty seat next to you will be permanently filled by me wherever we go." },
  { id: 60, question: "Open when you just want to feel my presence near you?", answer: "Wrap your arms around yourself, close your eyes, and feel the love I send you through this screen. I am right there with you in spirit." },
  { id: 61, question: "Open when you look at the gift I got for you?", answer: "That gift is just a tiny physical reflection of how much you mean to me. Whenever you look at it, remember that you are deeply cherished." },
  { id: 62, question: "Open when the distance between us feels tough?", answer: "Distance tests our patience, but it can never weaken our bond. Every mile between us right now will make being together under one roof infinitely sweeter." },
  { id: 63, question: "Open when you wish time would speed up so we can be together?", answer: "Time flies when we look back, and these waiting days will soon become a distant memory. Stay patient, my love — our forever is worth every second of waiting." },
  { id: 64, question: "Open when you think about names for our future children?", answer: "Our future kids are going to be blessed with the most loving, dignified, and beautiful mother on earth. I can't wait to build our family together." },
  { id: 65, question: "Open when life feels incomplete without me?", answer: "You complete my world in every way. Hold on tight, because every effort I make today is dedicated to bringing us together permanently." },
  { id: 66, question: "Open when I am traveling or away?", answer: "No matter how far I travel, my heart stays right where you are. Distance is just geography; you are my true home." },
  { id: 67, question: "Open when you feel like praying for our future together?", answer: "Prayers are the strongest bridge between us. May God protect our bond, bless our future steps, and join us together in pure happiness." },
  { id: 68, question: "Open when you remember the funniest moment we ever shared?", answer: "Laugh out loud! That moment was gold, and I promise you a lifetime full of goofy moments, joy, and tears of laughter together." },
  { id: 69, question: "Open when you are hungry late at night and don't know what to eat?", answer: "Midnight snack crisis! Grab something light and sweet right now, and make a note of what you crave so we can order it together next time." },
  { id: 70, question: "Open when you are feeling too lazy to get out of bed?", answer: "Stay under the covers five more minutes! Give yourself a gentle morning start — you don't have to rush into the world every single day." },
  { id: 71, question: "Open when you crave something sweet?", answer: "Nothing is sweeter than you, but go ahead and indulge in your favorite treat! You deserve a sweet mood boost today." },
  { id: 72, question: "Open when you watch a romantic movie and think of me?", answer: "Movie romances are cute, but they have nothing on our story. Our real love, respect, and growth beat any scripted movie scene." },
  { id: 73, question: "Open when your phone battery drops to 5%?", answer: "Quick! Plug in your phone before it dies! Don't worry about messaging back right away — charge up and rest your eyes." },
  { id: 74, question: "Open when you wake up early before everyone else?", answer: "Enjoy the quiet morning stillness. The world is peaceful, and you get a quiet moment to yourself before the day begins." },
  { id: 75, question: "Open when you have nothing to do and feel bored?", answer: "Boredom alert! Go check our 'Bucket List' tab on the site and add two new dreams or destinations you want us to experience together." },
  { id: 76, question: "Open when you look in the mirror and realize how gorgeous you are?", answer: "Finally, you see what I see every single second! Own your grace, your beauty, and your confidence today, queen!" },
  { id: 77, question: "Open when you are listening to soft music?", answer: "Let the music wash over you and relax your mind. Imagine us dancing quietly in our future living room to this exact rhythm." },
  { id: 78, question: "Open when you try cooking a new recipe?", answer: "Master chef Goji in action! Whether it turns out perfect or a total experiment, I would gladly eat anything made by your hands." },
  { id: 79, question: "Open when you feel playful and want to be spoiled?", answer: "Your wish is my command! Tell me what you want today — a sweet treat, a long story, or just endless compliments?" },
  { id: 80, question: "Open during a power outage or in the dark?", answer: "Don't be afraid of the dark. Remember that even in pitch darkness, my love for you shines bright like a steady light." },
  { id: 81, question: "Open when you hear someone call your name out of nowhere?", answer: "Your name is my favorite word in the entire Arabic language. Whenever I say 'Goji', my heart beats with genuine pride and love." },
  { id: 82, question: "Open when you discover a cool new feature on your phone?", answer: "Tech discovery! Share it with me right away so we can both test it out together!" },
  { id: 83, question: "Open when you sip a perfect cup of tea or coffee?", answer: "Enjoy that warm sip! May your day be as smooth, warm, and comforting as that perfect drink." },
  { id: 84, question: "Open when you find an old childhood photo of yourself?", answer: "Look at that little innocent face! You were adorable back then, and you grew up to be the most magnificent woman in the world." },
  { id: 85, question: "Open when you put on cozy, oversized clothes?", answer: "Maximum comfort mode activated! Enjoy feeling warm and snuggly today — you look adorable in comfy clothes." },
  { id: 86, question: "Open when you are hesitant about buying something?", answer: "If it brings you genuine value and joy, go for it! You work hard and you deserve to treat yourself without guilt." },
  { id: 87, question: "Open when you laugh out loud at something silly?", answer: "Hold onto that laughter! Hearing or imagining you laugh brings pure sunshine straight into my heart." },
  { id: 88, question: "Open when you can't bring yourself to put your phone down and sleep?", answer: "Put the phone face down right now, close your eyes, and take three slow breaths. Sleep comfortably — I'll be waiting for you in the morning." },
  { id: 89, question: "Open when you need a reminder of how precious you are to me?", answer: "You are irreplaceable. Out of everyone on this planet, you are the one my heart selected, cherished, and devoted itself to entirely." },
  { id: 90, question: "Open when you feel like nobody understands you?", answer: "I am here to understand, support, and validate you. Even when thoughts feel tangled, you can express them raw to me without fear." },
  { id: 91, question: "Open when you feel like you are being too hard on yourself?", answer: "Be gentle with yourself, Goji. You are human, growing, and doing the absolute best you can. Give yourself credit for how far you've come." },
  { id: 92, question: "Open when you feel carrying a heavy responsibility?", answer: "Take a pause. You don't have to fix everything in one day. Break it into small pieces, and remember I am standing right beside you to share the weight." },
  { id: 93, question: "Open when you need comforting words to soothe your heart?", answer: "May your heart find total peace today. You are protected, cherished, respected, and held in high regard every single day." },
  { id: 94, question: "Open when you need motivation to keep going?", answer: "Look at how much you have accomplished already! You have overcome tough days before, and you will breeze through this one too. Keep pushing!" },
  { id: 95, question: "Open when you need to feel safe and secure?", answer: "My love for you is an unshakeable fortress. No matter what changes around us, my loyalty and protection over you remain solid forever." },
  { id: 96, question: "Open when something breaks your heart?", answer: "I wish I could absorb your pain. Please let me comfort you. Whatever broke your heart today is temporary, but our love is an eternal shield." },
  { id: 97, question: "Open when you want to know why I chose you out of everyone?", answer: "Because you possess a rare blend of beauty, dignity, high character, and pure warmth that exists nowhere else. You are one of a kind." },
  { id: 98, question: "Open when you recall the positive impact you brought to my life?", answer: "Before you, life was ordinary. You brought purpose, joy, warmth, and a clear vision for the future. You made me a better man." },
  { id: 99, question: "Open when you want a fresh start to your day?", answer: "Wipe the slate clean right now! Yesterday is gone, today is a fresh gift, and you have every opportunity to make it beautiful." },
  { id: 100, question: "Open when you feel angry and struggling to stay calm?", answer: "Step back, take a deep breath, and hold your tongue until the anger passes. You are too wise and dignified to let temporary frustration win." },
  { id: 101, question: "Open when your day was filled with obstacles?", answer: "Tough days don't last, but resilient people do! Shake off the stress of today, get a good night's sleep, and reset for tomorrow." },
  { id: 102, question: "Open when a friend or relative upsets you?", answer: "Protect your inner peace. Not everything requires a reaction. Focus on what truly matters and let temporary misunderstandings slide." },
  { id: 103, question: "Open when you feel your hard work goes unappreciated?", answer: "I see your effort, I appreciate your dedication, and I value everything you do. Your hard work never goes unnoticed by me." },
  { id: 104, question: "Open when things don't go according to plan?", answer: "Sometimes detours lead to better destinations. Trust the process, adapt gracefully, and know that what is meant for you will never miss you." },
  { id: 105, question: "Open when you need to celebrate a small win?", answer: "Every step forward counts! Big success is made of tiny wins stacked together. Treat yourself — you earned it!" },
  { id: 106, question: "Open when your eyes are tired from looking at screens?", answer: "Close your eyes right now for two whole minutes. Rest your vision, stretch your neck, and step away from digital screens." },
  { id: 107, question: "Open when you need a boost of positive energy?", answer: "Sending you a wave of joy, strength, and pure affection right now! Smile, brighten up, and conquer your day!" },
  { id: 108, question: "Open when happiness feels far away?", answer: "Happiness is closer than you think — it's tucked in simple moments, in a warm drink, a quiet breath, and in knowing you are endlessly loved." },
  { id: 109, question: "Open when you want to read a long love letter?", answer: "Goji, my heart chose you with absolute certainty. You are my light, my pride, and my life partner. Every day I spend loving you is a blessing, and I will spend my entire life making you feel like the most cherished woman on earth." },
  { id: 110, question: "Open when you ask yourself, 'Is he thinking of me right now?'", answer: "The answer is a resounding YES! Whether I am coding, working, or walking, thoughts of you are constantly woven into my day." },
  { id: 111, question: "Open when you look up at the sky and think of our love?", answer: "Just like the vast sky above us, my love and devotion to you have no boundaries, no limits, and no end." },
  { id: 112, question: "Open when your heart is overflowing with love and needs an outlet?", answer: "Pour it out into our 'Thoughts Box' tab on the site! Write down every single feeling — I will treasure every word you leave for me." },
  { id: 113, question: "Open when you wake up to a sweet text from me?", answer: "Good morning, my world! I hope that text brought a wide smile to your face. May your day be as radiant as your heart." },
  { id: 114, question: "Open when you reflect on all the patience you have shown me?", answer: "Thank you for your patience, your understanding, and your unwavering belief in us. Your support means more to me than words can ever say." },
  { id: 115, question: "Open when you want to know how I view you in my future?", answer: "I see you as my wife, the queen of our home, my confidante, and the center of my world. Every future plan I draft revolves around you." },
  { id: 116, question: "Open when you are certain that you are my entire universe?", answer: "Your certainty is spot on! I am completely content with you, devoted to you, and I need nothing else from this world but your love." },
  { id: 117, question: "Open when you feel as completely content with me as I am with you?", answer: "Knowing that we bring each other total peace and fulfillment is the greatest achievement of my life. Together, we are complete." },
  { id: 118, question: "Open when your heart feels reserved for my love alone?", answer: "And my heart is permanently locked and key-held by you alone. A match made in heaven, sealed with respect and pure affection." },
  { id: 119, question: "Open when you think about how gently I care for you?", answer: "You deserve to be treated with ultimate tenderness, dignity, and care. I promise to always treat your heart like the precious jewel it is." },
  { id: 120, question: "Open when you feel that fate brought us together for a beautiful reason?", answer: "I believe with all my soul that God united our paths so we can build a loving, dignified life together. You are my greatest blessing." },
  { id: 121, question: "Open when you remember the very first time I said 'I love you'?", answer: "I said it with complete conviction back then, and every passing day proves how true those words were. I love you deeper today than ever before." },
  { id: 122, question: "Open when you just want to feel my presence in quiet comfort?", answer: "Sit back, take a slow breath, and feel the calm. You don't need to do anything right now — just enjoy the peace of being loved deeply." },
  { id: 123, question: "Open when you stare at our picture together?", answer: "Look at how happy we look! That picture is just a tiny glimpse of the endless joy waiting for us in our life together." },
  { id: 124, question: "Open when you see the morning sun rising?", answer: "Another day, another opportunity to love you, work for our future, and get one step closer to our dreams. Good morning, sunshine!" },
  { id: 125, question: "Open when you pray for God to protect us for each other?", answer: "Amen! May God protect our bond, grant us success, keep us safe from any harm, and unite us in everlasting happiness." },
  { id: 126, question: "Open when you are out with your friends having a great time?", answer: "Have the absolute best time! Laugh freely, enjoy the moments, and know I am happy seeing you happy." },
  { id: 127, question: "Open when you finally buy something you've wanted for a long time?", answer: "Yay! So glad you got it! Enjoy every second of using it — you deserve all the lovely things in life." },
  { id: 128, question: "Open when you need to be reminded that you are a princess in my eyes?", answer: "Crown up, Goji! You carry yourself with such grace and dignity that treating you like a princess comes naturally to me." },
  { id: 129, question: "Open when you think about the endless hours we spent talking on the phone?", answer: "Those late-night conversations are unforgettable. Time stands still whenever I talk to you, and I never get tired of your voice." },
  { id: 130, question: "Open when you feel how much you have grown and matured?", answer: "I see your wisdom and maturity blossoming every day. You handle life with such elegance, and I admire you deeply." },
  { id: 131, question: "Open when you think about choosing furniture for our future home?", answer: "I can't wait to pick out every color, rug, and couch with you! Decorating our safe space together will be a dream come true." },
  { id: 132, question: "Open when you feel that life became easier with me by your side?", answer: "And my life became infinitely brighter with you. We make each other stronger, calmer, and ready to face anything." },
  { id: 133, question: "Open when you want to feel the warmth of my emotions?", answer: "My love for you is warm, steady, and endless. It is a constant shelter you can always rely on, no matter what happens." },
  { id: 134, question: "Open when you imagine me laughing with you?", answer: "I can't wait for our next goofy moment! Laughing with you is my absolute favorite therapy." },
  { id: 135, question: "Open when you wake up to the sound of rain?", answer: "Listen to the rain drops tapping the window... warm tea, a quiet morning, and my endless love sent straight to your heart." },
  { id: 136, question: "Open when you feel playful and mischievous?", answer: "Uh oh, trouble! What playful scheme are you cooking up today? I am ready for your mischievous side!" },
  { id: 137, question: "Open when you think of a promise I made that I am working to keep?", answer: "A promise made to you is a sacred commitment. I am working hard every day to turn every word I promised you into reality." },
  { id: 138, question: "Open when you feel like the most beautiful girl in the world?", answer: "Because you ARE the most beautiful girl in the world! Inside and out, nobody compares to your charm and heart." },
  { id: 139, question: "Open when you need to hear that I will never let you go?", answer: "I am locked in forever. You are my choice, my devotion, and my life partner. I am never letting go of this precious bond." },
  { id: 140, question: "Open when you remember the first time we met?", answer: "That moment is etched in my memory forever. The day my life changed for the better, introducing me to my forever person." },
  { id: 141, question: "Open when you are thinking about making a fresh change in life?", answer: "Embrace growth! I support your ambitions 100%, and I will stand right behind you through every new adventure." },
  { id: 142, question: "Open when you feel like time is flying by?", answer: "Time flies when we are happy, and it's bringing us closer to our goal every day. Every ticking second is progress." },
  { id: 143, question: "Open when you look at this website and remember I built it for you?", answer: "Every line of code, every pixel, and every word on this site was crafted with deep love specifically for you, Goji." },
  { id: 144, question: "Open when you need an emotional hug through words?", answer: "Wrapping my arms tightly around your heart right now. Feel the warmth, the safety, and the deep affection I have for you." },
  { id: 145, question: "Open when you see the timer ticking, recording every second of our love?", answer: "Look at those numbers climb! Every single second recorded on that timer represents a moment I fell deeper in love with you." },
  { id: 146, question: "Open when you want to remind me of a shared favor or promise?", answer: "Reminder received! Message me directly right now and tell me what you need — your wishes are my top priority." },
  { id: 147, question: "Open for no reason at all — just because I love you endlessly?", answer: "No special occasion needed! Just a random, heartfelt reminder that you are adored, valued, and loved beyond measure." },
  { id: 148, question: "Open when you decide to turn off your phone and sleep peacefully?", answer: "Goodnight, my precious queen. Rest deeply, dream sweet dreams, and know that you are my entire world forever." },
  { id: 149, question: "Open when you want to know if I am proud of you?", answer: "I am prouder of you than words can ever express. Your character, your heart, and your presence make me walk tall every day." },
  { id: 150, question: "Open when you are ready to build our forever life together?", answer: "I am ready, committed, and working relentlessly every single day. Let's build our dream life, hand in hand, forever!" }
];

const loveReasons = [
  "Because your smile brightens up my darkest days instantly.",
  "Because your eyes hold a mesmerizing spell that hypnotizes me every time.",
  "Because of your angelic, innocent features that steal my heart over and over.",
  "Because you are gorgeous in every state, even right after waking up.",
  "Because your laugh has a beautiful ring that fills my heart with joy.",
  "Because of your gentle tone and feminine way of speaking.",
  "Because one look from you makes me feel like I own the entire world.",
  "Because your features are calm, peaceful, and soul-soothing.",
  "Because you bring grace and beauty into everything you do.",
  "Because your eyes narrow so cutely whenever you laugh hard.",
  "Because your beauty isn't just physical — it shines straight from your soul.",
  "Because of your elegant, flawless taste in everything you choose.",
  "Because your face exudes innocence, pure light, and serenity.",
  "Because you are the most captivating girl my eyes have ever seen.",
  "Because your beauty is so effortless and natural.",
  "Because every time I look at your photo, I discover a new detail to adore.",
  "Because even when you are serious or quiet, you look stunning.",
  "Because you captured my heart and eyes from the very first moment.",
  "Because your presence naturally draws all the attention in the room.",
  "Because the way you move and fix your hair looks like poetry.",
  "Because your shy blush when I compliment you melts my heart.",
  "Because your cute, playful side is utterly irresistible.",
  "Because your voice carries a warm tone that immediately calms me down.",
  "Because your facial details are so delicate and perfectly soft.",
  "Because whatever outfit you wear suddenly looks ten times better on you.",
  "Because you are the sweetest flower in the garden of my life.",
  "Because wherever you go, you bring vibrant joy with your charm.",
  "Because you are the moon that lights up the dark nights of my life.",
  "Because your unique charm and grace are truly peerless.",
  "Because you look like a masterpiece created with ultimate care.",
  "Because your self-respect and dignity grow my admiration for you daily.",
  "Because of your refined manners and polite way of treating everyone.",
  "Because your modesty adds immense value and beauty to who you are.",
  "Because of the pure, untainted nature of your kind heart.",
  "Because your noble upbringing shines through every single action you take.",
  "Because you hold high standards and never allow anyone to cross boundaries.",
  "Because your pride and dignity make me endlessly proud to have you.",
  "Because you speak with such high etiquette and respect to everyone.",
  "Because your love and devotion to your family show the purity of your roots.",
  "Because you understand true principles and always do the right thing.",
  "Because toxic or harsh words never cross your lips.",
  "Because of your composure and wisdom when handling tough situations.",
  "Because of how deeply you respect me and value my presence in your life.",
  "Because your decency and modesty make me hold my head high.",
  "Because you are dependable, strong, and reliable whenever things get real.",
  "Because your intentions are always pure, free of malice or resentment.",
  "Because your forgiving heart holds love and goodwill for everyone.",
  "Because of your genuine humility despite your incredible beauty and qualities.",
  "Because your trustworthiness makes me confide in you with complete peace.",
  "Because you honor every promise and covenant between us.",
  "Because you are wise, cultured, and express your thoughts with grace.",
  "Because your eyes reflect deep modesty in every glance.",
  "Because your responses are always articulate, polite, and considerate.",
  "Because you respect my feelings and never make light of my emotions.",
  "Because you are the definition of a partner anyone would dream to marry.",
  "Because you maintain clear, respectful boundaries with strangers.",
  "Because your high ethics allow me to trust you blindly and completely.",
  "Because you are faithful, grounded, and keep God in your heart and actions.",
  "Because your strong values give me strength and peace of mind.",
  "Because you honor and respect our privacy and personal boundaries.",
  "Because your tenderness wipes away all my stress and exhaustion.",
  "Because you treat me with overwhelming gentleness when I am down.",
  "Because you are the only one who can make me smile in my darkest moments.",
  "Because you understand me without requiring long explanations.",
  "Because you endure my mood swings and handle them with grace.",
  "Because you encourage me and remain my number one fan.",
  "Because you feel my emotions even when distance separates us.",
  "Because you listen to me patiently without ever getting bored.",
  "Because you give me a sense of security I find nowhere else.",
  "Because your warmth is genuine and comes straight from your core.",
  "Because you know how to comfort me in ways that melt away all anger.",
  "Because you truly care about me and pay attention to my smallest details.",
  "Because you share your thoughts and dreams with complete honesty.",
  "Because when I am with you, I feel like a safe, protected child.",
  "Because you place your complete trust in me and elevate my place in your life.",
  "Because you support my ambitions and see the absolute best in me.",
  "Because your care inspires me to become the best man I can be for you.",
  "Because you appreciate my circumstances and value every effort I make.",
  "Because you look after my health, comfort, and peace of mind.",
  "Because a single word from you gives me the energy to keep going.",
  "Because you never leave my side when times get tough.",
  "Because you genuinely share my joy and feel my pain as your own.",
  "Because you love me for who I truly am, without pretense.",
  "Because you are my safe haven whenever I need to escape the world.",
  "Because the way you care for me makes me feel cherished like a king.",
  "Because you are my best friend, partner, lover, and my whole world.",
  "Because you know when to give me space and when to pull me close.",
  "Because your big heart embraces all my flaws with unconditional love.",
  "Because you are the only one who penetrated deep into my soul like this.",
  "Because you constantly make me feel how important and valued I am.",
  "Because you are my entire universe and I see no one else but you.",
  "Because my eyes and heart are completely full with your presence alone.",
  "Because my ultimate dream is to marry you and build our warm home together.",
  "Because you are the exact vision of the mother I dream of for my children.",
  "Because in you, I found every quality I ever prayed for and more.",
  "Because life lost its flavor without you being the central part of it.",
  "Because you are the drive and goal behind all my hard work and ambition.",
  "Because thinking about a future with you fills my soul with hope.",
  "Because you are the ultimate, perfect life partner for the rest of my days.",
  "Because I cannot picture a single day of my future with anyone else.",
  "Because you are the beautiful blessing God granted to my life.",
  "Because every future step I take has your name written beside it.",
  "Because I want us to create a peaceful home filled with love and warmth.",
  "Because you are worth every piece of effort and hard work I put in.",
  "Because if I could relive life a hundred times, I would choose you every time.",
  "Because you build our dreams with me step by step with pure love.",
  "Because your presence makes me fight to achieve everything we dream of.",
  "Because you are the gift sent to illuminate my entire existence.",
  "Because all these reasons make me fall deeper in love with you every second.",
  "Because choosing you is the absolute best decision of my life.",
  "Because when you act playful and adorable, you are impossibly cute.",
  "Because of the adorable way you eat something you genuinely enjoy.",
  "Because of the sweet cadence in your voice whenever you call my name.",
  "Because of how irresistibly cute you look when you get shy and blush.",
  "Because of your spontaneous, charming, and fun-loving personality.",
  "Because of the endless laughter and joy we share together.",
  "Because we can understand each other completely with just a single glance.",
  "Because of the unique, genuine ways you express your love to me.",
  "Because of the thoughtful little details you remember about me to surprise me.",
  "Because you get excited like a happy child over the simplest things.",
  "Because you are the only person who can make me laugh from the bottom of my heart.",
  "Because of that subtle, cute jealousy that shows how much you care.",
  "Because of how animatedly you tell me every detail about your day.",
  "Because of the softness and elegance present in your every gesture.",
  "Because of the out-of-the-blue sweet messages you send that make my day.",
  "Because of our shared taste in music, movies, and little hobbies.",
  "Because of your adorable pouts that make me want to instantly spoil you.",
  "Because of how effortlessly you fix your hair or outfit.",
  "Because when you ask for something softly, I can never say no.",
  "Because your innocent antics make my heart skip a beat.",
  "Because of your intelligence in knowing the right moments to talk about deep things.",
  "Because of the soothing rhythm of your voice during late-night phone calls.",
  "Because of the genuine smile that lights your face when I make a joke.",
  "Because of your raw, honest, and unscripted reactions.",
  "Because you are my child, my lover, and my princess all at once.",
  "Because you are the sweetest reality amidst a noisy world.",
  "Because of your selfless giving nature without expecting anything in return.",
  "Because of your immaculate self-care, elegance, and neatness.",
  "Because when you talk about your future, your noble ambition shines through.",
  "Because you taught me the true meaning of genuine love.",
  "Because your eyes sparkle like stars whenever you get excited.",
  "Because holding your hand makes me feel like I hold the whole world.",
  "Because your comforting words make me feel like I am flying on cloud nine.",
  "Because of your deep loyalty and unshakeable devotion to us.",
  "Because of your refreshing simplicity and uncomplicated outlook on life.",
  "Because you complete me and fill every empty space in my soul.",
  "Because every day with you confirms that I made the best choice of my life.",
  "Because of the pure, unfiltered love I see in your eyes when you look at me.",
  "Because you are Goji — unmatched in your beauty, charm, and grace.",
  "Because simply put... you are my entire world, I am madly in love with you, and I am completely content with only you forever!"
];

/* Sanity guards so a future edit never silently drops content */
if (typeof window !== "undefined") {
  window.openWhenCards = openWhenCards;
  window.loveReasons = loveReasons;
}
